# config.yaml
training:
  batch_size: 32
  learning_rate: 5e-5
  epochs: 3
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: epoch
  save_strategy: epoch
  report_to: tensorboard

model:
  name: huawei-noah/TinyBERT_General_4L_312D
  ner_model_name: ner_animals_model

paths:
  training_output_dir: results 
  logging_dir_name: logs
  data_file: structured_data_animals.csv

labels:
  label_ids:
    - O
    - butterfly
    - cat
    - chicken
    - cow
    - dog
    - elephant
    - horse
    - sheep
    - spider
    - squirrel
